### ISSUE TITLE
Consider including features from OptiDoom

### ISSUE THREAD

**Issue by Danfun64** [BodbDearg/phoenix_doom#1]
https://github.com/Optimus6128/optidoom3do is one of the main projects working with the 3DO code. It's slightly more optimized than the original 3do Doom has some new features like PSX skies. You think you'd be able to port features to your codebase?

Conversely, I'm curious if some of your changes like the bug fixes could be backported to optidoom.

**Comment by BodbDearg** [comment]
Most of the changes in OptiDoom as I understand it are about trying to increase the framerate and get the game running at a faster clip on the original hardware, and as such are not really applicable to this project.

There are certainly a lot of fixes that could be incorporated from this port into OptiDoom however, I've listed some of these in the following file: https://github.com/BodbDearg/phoenix_doom/blob/master/docs/Differences%20To%203DO%20DOOM.md

As far as PSX skies go, I think I would rather keep 3DO Doom as it's own thing and not inter-mix the console versions. If someone wants to do this however they are more than welcome to fork the code and try it out! If you're interested in PSX DOOM, I also have a much more comprehensive project in the works right now: https://github.com/BodbDearg/StationDoom
